[mgr]
prepend_keymap = [
	{ on = "?",    run = "help", desc = "Open help" },
	{ on = [ "g", "p" ], run = "cd ~/projects"},
	{ on = [ "g", "c" ], run = "cd ~/.config/nixos"},
	{ on = [ "g", "n" ], run = "cd ~/notes"},
	{ on = [ "g", "d" ], run = "cd ~/Downloads"},
	{ on = [ "g", "m" ], run = "cd /run/media/nixos"},
	{ on = [ "g", "a" ], run = "cd ~/android_mount"},
	{ on = [ "g", "h" ], run = "cd ~"},
	{ on = [ "g", "r" ], run = "cd /"},
]
